dtb-$(CONFIG_ARCH_AXXIA) += axm5604-sim.dtb axm5608-sim.dtb axm5616-sim.dtb axm5601-emu.dtb axm5602-emu.dtb axm5606-emu.dtb axc6704-sim.dtb axc6716-sim.dtb axc6704-emu.dtb axc6712-emu.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
