# Makefile for the LSI FEMAC network interface.

obj-$(CONFIG_NET_LSI_MDIO) += lsi-mdio.o
obj-$(CONFIG_NET_LSI_FEMAC) += lsi-femac.o
obj-$(CONFIG_LSI_NET) += lsi_acp_mdio.o
obj-$(CONFIG_LSI_NET) += lsi_acp_net.o
